export const Users=[
    {
        id:1,
        profilePicture : "assests/person/5.jpeg",
        username: "Swakshwar Ghosh",
    },
    {
        id:2,
        profilePicture : "assests/person/2.jpeg",
        username: "Sarthak Mishra",
    },
    {
        id:3,
        profilePicture : "assests/person/10.jpeg",
        username: "Akshansh Garg",
    },
    {
        id:4,
        profilePicture : "assests/person/4.jpeg",
        username: "Krish Yadav",
    },
    {
        id:5,
        profilePicture : "assests/person/5.jpeg",
        username: "Ankit Kumar",
    },
    {
        id:6,
        profilePicture : "assests/person/6.jpeg",
        username: "Gaurav Patel",
    },
    {
        id:7,
        profilePicture : "assests/person/7.jpeg",
        username: "Ashwani Ahlawat",
    },
    {
        id:8,
        profilePicture : "assests/person/8.jpeg",
        username: "Dingo",
    },
    {
        id:9,
        profilePicture : "assests/person/9.jpeg",
        username: "Silver",
    },
    {
        id:10,
        profilePicture : "assests/person/10.jpeg",
        username: "Chandler",
    },
    {
        id:11,
        profilePicture : "assests/person/1.jpeg",
        username: "Gyan",
    },
]

export const Posts = [
    {
        id: 1,
        photo: "assests/post/1.jpeg",
        date: "5 min ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "I am better alone",
        photo: "assests/post/2.jpeg",
        date: "15 min ago",
        userId: 2,
        like: 2,
        comment: 19,
    },
    {
        id: 3,
        desc: "Love for all, hatred for one.",
        photo: "assests/post/3.jpeg",
        date: "10 min ago",
        userId: 3,
        like: 50,
        comment: 13,
    },
    {
        id: 4,
        desc: "My life is just like this-splitted in half",
        photo: "assests/post/4.jpeg",
        date: "9 min ago",
        userId: 4,
        like: 67,
        comment: 34,
    },
    {
        id: 5,
        desc: "My work is everything",
        photo: "assests/post/5.jpeg",
        date: "90 min ago",
        userId: 5,
        like: 69,
        comment: 31,
    },
    {
        id: 6,
        desc: "curiosity",
        photo: "assests/post/6.jpeg",
        date: "88 min ago",
        userId: 6,
        like: 72,
        comment: 10,
    },
    {
        id: 7,
        photo: "assests/post/7.jpeg",
        date: "55 min ago",
        userId: 7,
        like: 28,
        comment: 99,
    },
    {
        id: 8,
        desc:"Heaven :)",
        photo: "assests/post/8.jpeg",
        date: "50 min ago",
        userId: 8,
        like: 20,
        comment: 40,
    },
    {
        id: 9,
        photo: "assests/post/9.jpeg",
        date: "5 min ago",
        userId: 9,
        like: 32,
        comment: 9,
    },
    {
        id: 10,
        photo: "assests/post/10.jpeg",
        date: "1 min ago",
        userId: 10,
        like: 320,
        comment: 90,
    },
] 